### PR TITLE
fix(auth): resolved the login and registration

### LINKED ISSUE #64: [FRONTEND] Fix Login Page
fix errors in login page
connect to api

### PR DESCRIPTION
**Pull request by MohaAAlJ**
# 🚀 Registration Fix & Schema Modernization (SALOONY-64)

I’ve sorted out the architectural bugs that were blocking users from signing up and took the opportunity to update our core validation logic.

### 🛠️ What’s in this update:

*   **Registration Integrity**: Resolved the "400 Bad Request" cycle. I corrected the registration payload to send strictly lowercase `role` and `language` values, ensuring perfect synchronization with the backend's enum constraints.
*   **New Login Schema**: Implemented a new, strictly-typed validation contract for the login form (`login.ts`). This makes the authentication process significantly more robust and type-safe.
*   **Validation Architecture**: Refactored the registration schema to eliminate "magic numbers." I extracted constants for age limits (13–120) and simplified the date logic to keep the codebase clean and maintainable.
*   **Enhanced Error Feedback**: Optimized the Auth Provider error handling. The app now proactively displays the real backend response (like *"User already exists"*) instead of failing silently.

### 🚦 How to Test:
Run a fresh registration with a new email. Every field—from the phone number format to the final payload casing—is now perfectly aligned with the API requirements. 

Screenshot 2026-04-19 181238
Screenshot 2026-04-19 181347
Screenshot 2026-04-20 084341

### CODE REVIEW

File: src/utils/authOptions.ts [hunk 1]
```diff
@@ -43,6 +44,8 @@ export const authOptions: NextAuthOptions = {
             })
           });
 
+          console.log('Auth response status:', response.status);
```
Comment (hazzem-badran) [inline src/utils/authOptions.ts]: don't leave any console log

File: package.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
   "version": "3.5.1",
   "private": true,
   "scripts": {
-    "dev": "next dev --turbopack --port $PORT --hostname 0.0.0.0",
+    "dev": "next dev --turbopack --hostname 0.0.0.0",
```
Comment (hazzem-badran) [inline package.json:6]: Why did you do that?

Comment (MohaAAlJ) [reply package.json:6]: Screenshot 2026-04-21 122131

Comment (MohaAAlJ) [reply package.json:6]: it shows me this error message so i removed it and everything works so i followed the golden rule of "if it works don't touch it"

**Comment by MohaAAlJ** [comment]
Screenshot 2026-04-22 175139
Screenshot 2026-04-22 175148

File: src/sections/auth/social-links/style.ts [hunk 3]
```diff
@@ -4,64 +4,70 @@ import type { SxProps } from '@mui/system';
...
+  height: 47,
+  borderRight: '1px solid rgba(0, 0, 0, 0.5)',
   display: 'grid',
   placeItems: 'center'
 };
 
 export const iconStyle = (theme: Theme): SxProps<Theme> => ({
   fontSize: 24,
-  color: theme.palette.primary.main
+  color: '#A88D67' // Gold color for social icons
```
Comment (hazzem-badran) [inline src/sections/auth/social-links/style.ts]: Avoid hardcoding colors. Better to use theme.

File: src/views/auth/login.tsx [hunk 4]
```diff
@@ -34,19 +43,19 @@ export default function Login() {
 
             <Typography sx={noAccountTextStyle}>
               Don&apos;t have an account?{' '}
-              <Link component={NextLink} href="/register" sx={{ fontWeight: 'bold', ...noAccountTextStyle }}>
+              <NextLink href="/register" style={{ color: '#000000', textDecoration: 'none', fontWeight: 600 }}>
                 Create one
```
Comment (hazzem-badran) [inline src/views/auth/login.tsx:50]: Separate styles from the TSX file.

File: src/views/auth/login.tsx [hunk 5]
```diff
@@ -34,19 +43,19 @@ export default function Login() {
...
-              </Link>
+              </NextLink>
             </Typography>
 
             <Auth_Login />
           </Box>
         </Grid>
 
-        <Grid size={{ xs: 0, md: 6 }}>
+        <Grid size={{ xs: 0, md: 6 }} sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
```
Comment (hazzem-badran) [inline src/views/auth/login.tsx]: Separate styles from the TSX file.

File: src/views/auth/style.ts [hunk 6]
```diff
@@ -14,30 +14,53 @@ export const loginGridStyle: SxProps<Theme> = {
...
+  margin: 'auto'
 };
 
 export const noAccountTextStyle: SxProps<Theme> = {
-  mt: 3,
-  color: 'text.secondary',
+  mt: 2,
   textAlign: 'center',
-  letterSpacing: '0.08em'
+  color: '#7E7E7E',
```
Comment (hazzem-badran) [inline src/views/auth/style.ts]: and here

**Comment by MohaAAlJ** [comment]
Screenshot 2026-04-23 115443
Screenshot 2026-04-23 115449

**Review by hazzem-badran — APPROVED** [review]
